export const ADDSERVICE = 'ADDSERVICE';
export const ADDSERVICE_SECCESS = 'GET_ADDSERVICE_SUCCESS';
export const ADDSERVICE_ERROR = 'GET_ADDSERVICE_ERROR';

export const ADDAllSERVICE = 'ADDAllSERVICE';
export const ADDAllSERVICE_SECCESS = 'GET_ADDAllSERVICE_SUCCESS';
export const ADDAllSERVICE_ERROR = 'GET_ADDAllSERVICE_ERROR';

export const DELETESERVICE = 'DELETESERVICE';
export const DELETESERVICE_SECCESS = 'GET_DELETESERVICE_SUCCESS';
export const DELETESERVICE_ERROR = 'GET_DELETESERVICE_ERROR';

export const GETBYIDSERVICE = 'GETBYIDSERVICE';
export const GETBYIDSERVICE_SECCESS = 'GETBYIDSERVICE_SUCCESS';
export const GETBYIDSERVICE_ERROR = 'GETBYIDSERVICE_ERROR';