export const UPDATESHOP = 'UPDATESHOP';
export const UPDATESHOP_SECCESS = 'GET_UPDATESHOP_SUCCESS';
export const UPDATESHOP_ERROR = 'GET_UPDATESHOP_ERROR';

export const SHOP = 'SHOP';
export const SHOP_SECCESS = 'GET_SHOP_SUCCESS';
export const SHOP_ERROR = 'GET_SHOP_ERROR';

export const DELETESHOP = 'DELETESHOP';
export const DELETESHOP_SECCESS = 'GET_DELETESHOP_SUCCESS';
export const DELETESHOP_ERROR = 'GET_DELETESHOP_ERROR';