export const ADDVOUCHER = 'ADDVOUCHER';
export const ADDVOUCHER_SECCESS = 'GET_ADDVOUCHER_SUCCESS';
export const ADDVOUCHER_ERROR = 'GET_ADDVOUCHER_ERROR';

export const ADDAllVOUCHER = 'ADDAllVOUCHER';
export const ADDAllVOUCHER_SECCESS = 'GET_ADDAllVOUCHER_SUCCESS';
export const ADDAllVOUCHER_ERROR = 'GET_ADDAllVOUCHER_ERROR';

export const DELETEVOUCHER = 'DELETEVOUCHER';
export const DELETEVOUCHER_SECCESS = 'GET_DELETEVOUCHER_SUCCESS';
export const DELETEVOUCHER_ERROR = 'GET_DELETEVOUCHER_ERROR';

export const GETBYIDVOUCHER = 'GETBYIDVOUCHER';
export const GETBYIDVOUCHER_SECCESS = 'GETBYIDVOUCHER_SUCCESS';
export const GETBYIDVOUCHER_ERROR = 'GETBYIDVOUCHER_ERROR';