
export const ADDAllUSER = 'ADDAllUSER';
export const ADDAllUSER_SECCESS = 'GET_ADDAllUSER_SUCCESS';
export const ADDAllUSER_ERROR = 'GET_ADDAllUSER_ERROR';


export const DELETEUSER = 'DELETEUSER';
export const DELETEUSER_SECCESS = 'GET_DELETEUSER_SUCCESS';
export const DELETEUSER_ERROR = 'GET_DELETEUSER_ERROR';