export const UPDATEAPPOINTMENT = 'UPDATEAPPOINTMENT';
export const UPDATEAPPOINTMENT_SECCESS = 'GET_UPDATEAPPOINTMENT_SUCCESS';
export const UPDATEAPPOINTMENT_ERROR = 'GET_UPDATEAPPOINTMENT_ERROR';

export const APPOINTMENT = 'APPOINTMENT';
export const APPOINTMENT_SECCESS = 'GET_APPOINTMENT_SUCCESS';
export const APPOINTMENT_ERROR = 'GET_APPOINTMENT_ERROR';

export const DELETEAPPOINTMENT = 'DELETEAPPOINTMENT';
export const DELETEAPPOINTMENT_SECCESS = 'GET_DELETEAPPOINTMENT_SUCCESS';
export const DELETEAPPOINTMENT_ERROR = 'GET_DELETEAPPOINTMENT_ERROR';